intro: |
  Property Based Testing (PBT) is a way of writing unit tests that views test coverage from a 
  different perspective. PBT is a form of _contract based programming_.

  The following guide provides an overview and comparison of PBT to traditional unit testing. It 
  also provides useful links for developers planning to investigate the subject further.

guides:
  - Property Based Testing/PBT Introduction
