intro: |
  Python has evolved over the years and is one of the most popular programming languages.

  The following guide is focusing on writing readable and cleaner code in Python. It is part of a planned series of articles.

guides:
  - Programming Languages/Python Tips
