intro: |
  A great way to share knowledge and experience is through video recordings of an 
  actual programming session.

  The following guides introduce a curated series of videos which explores extreme 
  programming technique videos.

guides:
  - Video Series/Video Series Introduction
  - Video Series/What If
